[workspace]

resolver = "2"
members = [
	"clock",
	"hardware-tests/test-display",
	"hardware-tests/test-isr-edge",
	"hardware-tests/test-isr-timer",
	"hardware-tests/test-ky040",
	"hardware-tests/test-leds",
]
