[package]
name = "test-isr-timer"
version = "0.1.1"
edition = "2021"

[dependencies]
cortex-m-rt = "0.7"
defmt-rtt = "0.4"
embedded-hal = { version = "0.2.7", features = ["unproven"] }
fugit = "0.3"
panic-halt = "0.2"

rp-pico = "0.8"
