[package]
name = "test-display"
version = "0.1.1"
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
defmt-rtt = "0.4"
embedded-hal = { version = "0.2.7", features = ["unproven"] }
fugit = "0.3"
hd44780-driver = "0.4"
heapless = "0.7"
panic-halt = "0.2"

rp-pico = "0.6"
