[package]
name = "test-serial"
version = "0.7.0"
edition = "2021"

[dependencies]
cortex-m-rt = "0.7"
defmt-rtt = "0.4"
embedded-hal = { version = "0.2.7", features = ["unproven"] }
heapless = "0.7"
panic-halt = "0.2"
usbd-serial = "0.1"
usb-device = "0.2"

rp-pico = "0.7"
